[package]
org = "ballerinax"
name = "cdata"
version = "0.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["CData","Jira"]
export = ["cdata", "cdata.jira"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./cdataDrivers/cdata.jdbc.jira.jar"
modules = ["cdata_jira"]
