[package]
org = "rolandhewage"
name = "cdatatest.jira"
version = "0.1.0"
license= ["Apache-2.0"]
authors = ["Roland"]
keywords = ["CData","Jira"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./cdataDrivers/cdata.jdbc.jira.jar"
modules = ["cdata_jira"]
